project:
  type: website
  output-dir: docs

website:
  title: "Joshua Arias | Portfolio"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Portfolio"
        menu:
          - text: "Vamonos"
            href: vamonos.qmd
          - text: "Knight Cap"
            href: knightcap.qmd
          - text: "The Hair Shop"
            href: thehairshop.qmd
          - text: "NOJUNK"
            href: nojunk.qmd
      - text: "ABLISS"
        href: abliss.qmd
      - text: "Arias Collective"
        href: arias-collective.qmd
      - text: "Resume"
        href: resume.qmd


format:
  html:
    theme: default
    css: styles.css
    toc: true
