project:
  type: website

website:
  title: "Joshua Arias | Portfolio"
  navbar:
    left:
      - text: "Home"
        file: index.qmd
      - text: "Dashboard"
        file: dashboard.qmd
      - text: "Shiny App Essay"
        file: shiny-essay.qmd
      - text: "Shinylive Essay"
        file: shinylive-essay.qmd

format:
  html:
    theme: cosmo
    css: styles.css
