project:
  type: website
  output-dir: docs

website:
  title: "Joshua Arias | Portfolio"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Portfolio"
        menu:
          - text: "Vamonos"
            href: Case-Studies/vamonos.html
          - text: "Knight Cap"
            href: Case-Studies/Knightcap.html
          - text: "The Hair Shop"
            href: Case-Studies/thehairshop.html
          - text: "NOJUNK"
            href: Case-Studies/nojunk.html
      - text: "ABLISS"
        href: abliss.qmd
      - text: "Arias Collective"
        href: arias-collective.qmd
      - text: "Resume"
        href: resume.qmd

format:
  html:
    theme: default
    css: styles.css
    toc: true
